---
title: "Draft"
subtitle: "STA 210 - Project"
author: "Ginger and Stats - Aimi Wen, Rakshita Ramakrishna, Nathan Nguyen"
format: pdf
editor: visual
---

```{r}
#| label: load-pkg-data
#| warning: false
library(tidyverse)
library(tidymodels)
library(tidytext)
library(patchwork)
library(stringr)


library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
chocolate <- read_csv("../data/chocolate.csv")

world <- ne_countries(scale = "medium", returnclass = "sf")

```

# Exploratory Data Analysis

## Data description

## Analysis approach

## Shape of Ratings (already done)

...

## Cocoa Percent (Aimi)

```{r}
#| label: cocoa-percent

chocolate$cocoa_percent <- as.numeric(gsub('[,%]', '', chocolate$cocoa_percent))

chocolate$rating <- as.character(chocolate$rating) 

ggplot(data= chocolate, aes(x= cocoa_percent)) + geom_histogram() 

ggplot(data= chocolate, aes(x= cocoa_percent, y= rating)) + geom_boxplot()

chocolate$rating <- as.numeric(chocolate$rating) 
```

## Ingredients (Nathan)

```{r}
chocolate <- chocolate %>%
  mutate(lecithin = case_when(
    grepl("L", ingredients) ~ 1,
    T ~ 0
  ),
  vanilla = case_when(
    grepl("V", ingredients) ~ 1,
    T ~ 0
  ),
  cocoa = case_when(
    grepl("C", ingredients) ~ 1,
    T ~ 0
  ),
  salt = case_when(
    grepl("Sa", ingredients) ~ 1,
    T ~ 0
  ),
  
  lecithin = as.factor(lecithin),
  vanilla = as.factor(vanilla),
  cocoa = as.factor(cocoa),
  salt = as.factor(salt)
  )
```

```{r}
pL <- ggplot(chocolate, aes(lecithin, fill = as.factor(rating))) +
  geom_bar(position = "fill")+
  theme(legend.position = "none")
pV <- ggplot(chocolate, aes(vanilla, fill = as.factor(rating))) +
  geom_bar(position = "fill")+
  theme(legend.position = "none")
pC <- ggplot(chocolate, aes(cocoa, fill = as.factor(rating))) +
  geom_bar(position = "fill")+
  theme(legend.position = "none")
pSa <- ggplot(chocolate, aes(salt, fill = as.factor(rating))) +
  geom_bar(position = "fill")

(pL + pV)/(pC + pSa)

```

```{r}
chocolate <- chocolate %>%
  mutate(
    num_ingres = if_else(is.na(ingredients), "0", str_sub(ingredients, 1, 1))
  )
```

```{r}
chocolate %>%
  drop_na(
    ingredients
  ) %>%
  count()
```

```{r}
ggplot(chocolate, aes(num_ingres))+
  geom_bar()+
  labs(
    title = "Distribution of number of ingredients",
    x = "Number of ingredients"
  )
```

## Most Memorable Characteristic (Aimi)

```{r}
#| label: memorable-char

tidy_chocolate<- chocolate %>% 
  unnest_tokens(word, most_memorable_characteristics)

tidy_chocolate %>% 
  group_by(word) %>% 
  summarize( n= n(), 
             rating= mean(rating) ) %>%
  ggplot(aes(n, rating)) + 
  geom_hline(yintercept= mean(chocolate$rating)) + 
  geom_jitter(color= "blue", alpha= 0.5) + 
  geom_text(aes(label= word),
            check_overlap= TRUE, 
            vjust= "top", 
            hjust= "left") +
  scale_x_log10() 
```

## Country Bean of Origin (Rakshita)

```{r}
#| label: country-bean-of-origin

chocolate_modified <- chocolate %>%
  mutate(name_long = country_of_bean_origin) %>%
  group_by(name_long) %>%
  count(name_long)

chocworld_data <- world %>%
  full_join(y = chocolate_modified,
  by = "name_long") %>%
  mutate(numBars = ifelse(is.na(n), 0, n))

ggplot(data = chocworld_data) +
  scale_fill_gradient(low = "#F0FEFB", high = "#044F3F") +
  geom_sf(aes(fill = numBars, geometry = geometry)) +
  labs(title = "Map of countries where cacao beans were produced")
```

## Company Location (Rakshita)

```{r}
#| label: country-location

chocolate_modified2 <- chocolate %>%
  mutate(name_long = case_when(
    company_location == "U.S.A." ~ "United States",
    company_location == "U.K." ~ "United Kingdom",
    company_location == company_location ~ company_location)) %>%
  group_by(name_long) %>%
  count(name_long)
         
chocworld_data1 <- world %>%
  full_join(y = chocolate_modified2,
  by = "name_long") %>%
  mutate(numBars = ifelse(is.na(n), 0, n))

ggplot(data = chocworld_data1) +
  scale_fill_gradient(low = "#ffffff", high = "#044F3F") +
  geom_sf(aes(fill = numBars, geometry = geometry)) +
  labs(title = "Map of countries where companies are located")

chocolate %>%
    count(company_location, sort = TRUE)


```

## Review Date (Nathan)

```{r}
ggplot(chocolate, aes(review_date))+
  geom_bar()
```

```{r}
#| label: review date statistics

# statistics of review dates

chocolate %>%
  summarise(mean = mean(review_date),
            median = median(review_date),
            sd = sd(review_date))
```

```{r}
#review date vs cocoa_percent and ratings

chocolate <- chocolate %>%
  mutate(
    date_fct = as.factor(review_date)
  )

ggplot(chocolate, aes(date_fct, cocoa_percent))+
  geom_boxplot()+
  coord_flip()

ggplot(chocolate, aes(date_fct, fill = as.factor(rating)))+
  geom_bar(position = "fill")+
  coord_flip()+
  scale_fill_viridis_d()
```

```{r}
#| label: most-memorable-cleaning

chocolate_clean <- chocolate %>%
  separate(most_memorable_characteristics, sep= ",", into= c("most_memorable", "other_memorable"), extra= "merge") %>%
  select(-other_memorable) 


```

```{r}
chocolate_clean %>%
  count(most_memorable, sort= TRUE)
```

# Data

The data dictionary can be found [here](ADD%20LINK!!!).
